const REMOVEHEADER = 'AUTH_REMOVEHEADER';
const SETUSERDATA = 'AUTH_SETUSERDATA';
const SETHEADERS = 'AUTH_SETHEADERS';
const ADDHEADER = 'AUTH_ADDHEADER';
const SETUSERID = 'AUTH_SETUSERID';
const SETTOKEN = 'AUTH_SETTOKEN';

const types = {
    REMOVEHEADER,
    SETUSERDATA,
    SETHEADERS,
    ADDHEADER,
    SETUSERID,
    SETTOKEN,
};

export default types;
